/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Report process liveness plus a best-effort database connectivity check.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Repo
         * @description Connect a repository and enqueue its first ingest.
         *
         *     Idempotent on ``full_name``: reconnecting an existing repo updates the
         *     stored token (if provided) and re-enqueues ingestion only when the
         *     previous one failed — a healthy repo is not re-ingested by accident.
         */
        post: operations["connect_repo_api_repos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repo
         * @description Repository metadata + ingest status + latest job + entity counts.
         */
        get: operations["get_repo_api_repos__repo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description Paginated entity listing with kind filter, sort, and name/path search.
         *
         *     Bulky meta payloads (doc/section text, issue bodies) are stripped from
         *     list responses — detail-level content ships with the feed/claims APIs.
         */
        get: operations["list_entities_api_repos__repo_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Findings for the Truth Feed, newest first. ``status`` defaults to
         *     open (pass explicitly to see actioned/dismissed history).
         */
        get: operations["list_findings_api_repos__repo_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finding Action
         * @description Human-in-the-loop actions on a finding (architecture §12: writes to
         *     customer repos happen only behind an explicit click).
         */
        post: operations["finding_action_api_findings__finding_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_api_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/simulate-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Event */
        post: operations["simulate_event_api_repos__repo_id__simulate_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnchorOut
         * @description Source location of a claim (repo-relative).
         */
        AnchorOut: {
            /** Path */
            path?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
        };
        /** ClaimBrief */
        ClaimBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Statement */
            statement: string;
            claim_type: components["schemas"]["ClaimType"];
            status: components["schemas"]["ClaimStatus"];
            anchor: components["schemas"]["AnchorOut"];
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "unchecked" | "verified" | "stale" | "contradicted";
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "behavior" | "architecture" | "process" | "status";
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "code_file" | "symbol" | "doc" | "doc_section" | "issue" | "pull_request" | "person";
        /** EntityOut */
        EntityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["EntityKind"];
            /** Name */
            name: string;
            /** Path */
            path: string | null;
            /** External Id */
            external_id: string | null;
            /** Content Hash */
            content_hash: string | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EntityPage */
        EntityPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["EntityOut"][];
        };
        /** EventAccepted */
        EventAccepted: {
            /** Status */
            status: string;
            /** Event Id */
            event_id?: string | null;
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * EventBrief
         * @description Provenance: the reality event that triggered this finding.
         */
        EventBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["EventKind"];
            /** External Id */
            external_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "push" | "pr_merged" | "issue_closed" | "simulated";
        /**
         * EvidenceOut
         * @description Structured evidence: quoted spans plus an optional unified diff.
         */
        EvidenceOut: {
            /**
             * Quotes
             * @default []
             */
            quotes: components["schemas"]["EvidenceQuote"][];
            /** Diff */
            diff?: string | null;
        };
        /**
         * EvidenceQuote
         * @description One quoted span of evidence, optionally anchored to code.
         */
        EvidenceQuote: {
            /** Text */
            text: string;
            /** Path */
            path?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** Language */
            language?: string | null;
        };
        /** FindingActionRequest */
        FindingActionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "generate_fix" | "dismiss";
        };
        /** FindingActionResponse */
        FindingActionResponse: {
            /** Status */
            status: string;
            finding_status: components["schemas"]["FindingStatus"];
            /** Job Id */
            job_id?: string | null;
            /** Pr Url */
            pr_url?: string | null;
        };
        /**
         * FindingKind
         * @enum {string}
         */
        FindingKind: "doc_drift" | "stale_issue" | "contradiction" | "silo";
        /** FindingOut */
        FindingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["FindingKind"];
            severity: components["schemas"]["FindingSeverity"];
            status: components["schemas"]["FindingStatus"];
            /** Explanation */
            explanation: string;
            /** Suggested Action */
            suggested_action: string | null;
            evidence: components["schemas"]["EvidenceOut"];
            claim: components["schemas"]["ClaimBrief"];
            event: components["schemas"]["EventBrief"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FindingPage */
        FindingPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["FindingOut"][];
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "low" | "medium" | "high" | "critical";
        /**
         * FindingStatus
         * @enum {string}
         */
        FindingStatus: "open" | "actioned" | "dismissed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Shape of the /healthz payload (also lands in the OpenAPI schema).
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Database */
            database: string;
        };
        /**
         * IngestStatus
         * @enum {string}
         */
        IngestStatus: "pending" | "ingesting" | "ready" | "failed";
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "ingest" | "verify" | "generate_fix";
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "succeeded" | "failed";
        /**
         * RepoCreate
         * @description Connect a repository. ``token`` is a fine-grained PAT scoped to the
         *     repo; it is persisted server-side and never returned by any endpoint.
         */
        RepoCreate: {
            /**
             * Full Name
             * @example owner/repository
             */
            full_name: string;
            /** Token */
            token?: string | null;
        };
        /**
         * RepoDetail
         * @description Repo + pipeline visibility: latest job (progress/errors) and entity
         *     counts by kind (empty until the first ingest lands).
         */
        RepoDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Provider */
            provider: string;
            /** Default Branch */
            default_branch: string;
            ingest_status: components["schemas"]["IngestStatus"];
            /** Last Ingested Sha */
            last_ingested_sha: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Entity Counts */
            entity_counts: {
                [key: string]: number;
            };
            latest_job: components["schemas"]["JobOut"] | null;
        };
        /**
         * SimulateRequest
         * @description A canned GitHub-style webhook: same event names, same payload
         *     shapes, run through the identical normalization + pipeline.
         */
        SimulateRequest: {
            /**
             * Event
             * @example push
             * @example pull_request
             * @example issues
             */
            event: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** External Id */
            external_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    connect_repo_api_repos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repo_api_repos__repo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_repos__repo_id__entities_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["EntityKind"] | null;
                /** @description search name/path */
                q?: string | null;
                sort?: "name" | "path" | "kind" | "updated_at";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_repos__repo_id__findings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FindingStatus"] | null;
                severity?: components["schemas"]["FindingSeverity"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_action_api_findings__finding_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_api_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-github-event"?: string;
                "x-github-delivery"?: string;
                "x-hub-signature-256"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_event_api_repos__repo_id__simulate_event_post: {
        parameters: {
            query?: never;
            header?: {
                "x-axon-simulate-secret"?: string | null;
            };
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
