/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Report process liveness plus a best-effort database connectivity check.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Github Login */
        get: operations["github_login_api_auth_github_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Github Callback */
        get: operations["github_callback_api_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Repo
         * @description Connect a repository and enqueue its first ingest. Requires sign-in;
         *     the repo is owned by the connecting user.
         *
         *     Idempotent on ``full_name``: reconnecting an existing repo updates the
         *     stored token (if provided) and re-enqueues ingestion only when the
         *     previous one failed — a healthy repo is not re-ingested by accident. A
         *     legacy null-owner repo is claimed by the connecting user.
         */
        post: operations["connect_repo_api_repos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repo
         * @description Repository metadata + ingest status + latest job + entity counts.
         */
        get: operations["get_repo_api_repos__repo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description Paginated entity listing with kind filter, sort, and name/path search.
         *
         *     Bulky meta payloads (doc/section text, issue bodies) are stripped from
         *     list responses — detail-level content ships with the feed/claims APIs.
         */
        get: operations["list_entities_api_repos__repo_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Findings for the Truth Feed, newest first. ``status`` defaults to
         *     open (pass explicitly to see actioned/dismissed history).
         */
        get: operations["list_findings_api_repos__repo_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finding Action
         * @description Human-in-the-loop actions on a finding (architecture §12: writes to
         *     customer repos happen only behind an explicit click).
         */
        post: operations["finding_action_api_findings__finding_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/available-repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available Repos */
        get: operations["available_repos_api_github_available_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/pulls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pulls
         * @description Open pull requests, each annotated with the review state of its
         *     CURRENT revision (head_sha) so a new push visibly clears the review.
         */
        get: operations["list_pulls_api_repos__repo_id__pulls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/pulls/{pr_number}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description The most recent stored review for this pull request.
         */
        get: operations["get_review_api_repos__repo_id__pulls__pr_number__review_get"];
        put?: never;
        /**
         * Request Review
         * @description Enqueue an AI review of this pull request. Deduped: an in-flight job
         *     for the same PR is not enqueued twice.
         */
        post: operations["request_review_api_repos__repo_id__pulls__pr_number__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/pulls/{pr_number}/review/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Review
         * @description Publish the stored review to GitHub as the Axon app's bot identity.
         *     The explicit human-in-the-loop click — Axon never posts on its own.
         */
        post: operations["post_review_api_repos__repo_id__pulls__pr_number__review_post_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_api_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/simulate-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Event
         * @description Inject a synthetic reality event (demo/debug surface).
         *
         *     This drives real ingest/verify work, so it is gated twice: the caller must
         *     be signed in AND own the repository. The shared secret is an additional
         *     lock when configured — and in production it is mandatory, because an
         *     unconfigured secret used to skip the check entirely.
         */
        post: operations["simulate_event_api_repos__repo_id__simulate_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Kind */
            kind: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Repo Full Name */
            repo_full_name: string;
            /** Title */
            title: string;
            /** Pr Url */
            pr_url?: string | null;
            /** Reason */
            reason?: string | null;
            /** At */
            at: string;
        };
        /**
         * AnchorOut
         * @description Source location of a claim (repo-relative).
         */
        AnchorOut: {
            /** Path */
            path?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
        };
        /** AvailableRepo */
        AvailableRepo: {
            /** Full Name */
            full_name: string;
            /** Private */
            private: boolean;
            /** Description */
            description?: string | null;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Repo Id */
            repo_id?: string | null;
        };
        /** AvailableReposOut */
        AvailableReposOut: {
            /** Repos */
            repos: components["schemas"]["AvailableRepo"][];
            /** Install Url */
            install_url?: string | null;
        };
        /** ClaimBrief */
        ClaimBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Statement */
            statement: string;
            claim_type: components["schemas"]["ClaimType"];
            status: components["schemas"]["ClaimStatus"];
            anchor: components["schemas"]["AnchorOut"];
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "unchecked" | "verified" | "stale" | "contradicted";
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "behavior" | "architecture" | "process" | "status";
        /** DashboardOut */
        DashboardOut: {
            totals: components["schemas"]["Totals"];
            /** Repos */
            repos: components["schemas"]["RepoSummary"][];
            /** Recent Activity */
            recent_activity: components["schemas"]["ActivityItem"][];
        };
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "code_file" | "symbol" | "doc" | "doc_section" | "issue" | "pull_request" | "person";
        /** EntityOut */
        EntityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["EntityKind"];
            /** Name */
            name: string;
            /** Path */
            path: string | null;
            /** External Id */
            external_id: string | null;
            /** Content Hash */
            content_hash: string | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EntityPage */
        EntityPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["EntityOut"][];
        };
        /** EventAccepted */
        EventAccepted: {
            /** Status */
            status: string;
            /** Event Id */
            event_id?: string | null;
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * EventBrief
         * @description Provenance: the reality event that triggered this finding.
         */
        EventBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["EventKind"];
            /** External Id */
            external_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "push" | "pr_merged" | "issue_closed" | "simulated";
        /**
         * EvidenceOut
         * @description Structured evidence: quoted spans plus an optional unified diff.
         */
        EvidenceOut: {
            /**
             * Quotes
             * @default []
             */
            quotes: components["schemas"]["EvidenceQuote"][];
            /** Diff */
            diff?: string | null;
        };
        /**
         * EvidenceQuote
         * @description One quoted span of evidence, optionally anchored to code.
         */
        EvidenceQuote: {
            /** Text */
            text: string;
            /** Path */
            path?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** Language */
            language?: string | null;
        };
        /** FindingActionRequest */
        FindingActionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "generate_fix" | "dismiss";
        };
        /** FindingActionResponse */
        FindingActionResponse: {
            /** Status */
            status: string;
            finding_status: components["schemas"]["FindingStatus"];
            /** Job Id */
            job_id?: string | null;
            /** Pr Url */
            pr_url?: string | null;
        };
        /**
         * FindingKind
         * @enum {string}
         */
        FindingKind: "doc_drift" | "stale_issue" | "contradiction" | "silo";
        /** FindingOut */
        FindingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["FindingKind"];
            severity: components["schemas"]["FindingSeverity"];
            status: components["schemas"]["FindingStatus"];
            /** Explanation */
            explanation: string;
            /** Suggested Action */
            suggested_action: string | null;
            evidence: components["schemas"]["EvidenceOut"];
            claim: components["schemas"]["ClaimBrief"];
            event: components["schemas"]["EventBrief"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Pr Url */
            pr_url?: string | null;
        };
        /** FindingPage */
        FindingPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["FindingOut"][];
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "low" | "medium" | "high" | "critical";
        /**
         * FindingStatus
         * @enum {string}
         */
        FindingStatus: "open" | "actioned" | "dismissed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Shape of the /healthz payload (also lands in the OpenAPI schema).
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Database */
            database: string;
        };
        /**
         * IngestStatus
         * @enum {string}
         */
        IngestStatus: "pending" | "ingesting" | "ready" | "failed";
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "ingest" | "verify" | "generate_fix" | "review_pr";
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "succeeded" | "failed";
        /** PullListOut */
        PullListOut: {
            /** Items */
            items: components["schemas"]["PullOut"][];
        };
        /** PullOut */
        PullOut: {
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Head Sha */
            head_sha: string;
            /** Draft */
            draft: boolean;
            /** Url */
            url: string;
            /** Updated At */
            updated_at: string | null;
            review_status?: components["schemas"]["ReviewStatus"] | null;
            /** Review Url */
            review_url?: string | null;
            /**
             * Review Comment Count
             * @default 0
             */
            review_comment_count: number;
            /**
             * Review Pending
             * @default false
             */
            review_pending: boolean;
        };
        /**
         * RepoCreate
         * @description Connect a repository. ``token`` is a fine-grained PAT scoped to the
         *     repo; it is persisted server-side and never returned by any endpoint.
         */
        RepoCreate: {
            /**
             * Full Name
             * @example owner/repository
             */
            full_name: string;
            /** Token */
            token?: string | null;
        };
        /**
         * RepoDetail
         * @description Repo + pipeline visibility: latest job (progress/errors) and entity
         *     counts by kind (empty until the first ingest lands).
         */
        RepoDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Provider */
            provider: string;
            /** Default Branch */
            default_branch: string;
            ingest_status: components["schemas"]["IngestStatus"];
            /** Last Ingested Sha */
            last_ingested_sha: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Entity Counts */
            entity_counts: {
                [key: string]: number;
            };
            latest_job: components["schemas"]["JobOut"] | null;
        };
        /** RepoSummary */
        RepoSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Ingest Status */
            ingest_status: string;
            /**
             * Findings Open
             * @default 0
             */
            findings_open: number;
            /**
             * Findings Actioned
             * @default 0
             */
            findings_actioned: number;
            /**
             * Findings Dismissed
             * @default 0
             */
            findings_dismissed: number;
            /**
             * Prs Opened
             * @default 0
             */
            prs_opened: number;
        };
        /** ReviewCommentOut */
        ReviewCommentOut: {
            /** Path */
            path: string;
            /** Line */
            line: number;
            /**
             * Lens
             * @enum {string}
             */
            lens: "code" | "truth";
            /** Severity */
            severity: string;
            /** Body */
            body: string;
            /** Confidence */
            confidence?: number | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pr Number */
            pr_number: number;
            /** Head Sha */
            head_sha: string;
            /** Pr Title */
            pr_title: string | null;
            /** Summary */
            summary: string | null;
            /** Comments */
            comments: components["schemas"]["ReviewCommentOut"][];
            status: components["schemas"]["ReviewStatus"];
            /** Review Url */
            review_url: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReviewRequestResponse */
        ReviewRequestResponse: {
            /** Status */
            status: string;
            /** Job Id */
            job_id?: string | null;
            review?: components["schemas"]["ReviewOut"] | null;
        };
        /**
         * ReviewStatus
         * @description Lifecycle of an AI review of a pull request. Mirrors FixStatus: the
         *     review is generated and stored, then posted only on an explicit click.
         * @enum {string}
         */
        ReviewStatus: "generated" | "posted" | "failed";
        /**
         * SimulateRequest
         * @description A canned GitHub-style webhook: same event names, same payload
         *     shapes, run through the identical normalization + pipeline.
         */
        SimulateRequest: {
            /**
             * Event
             * @example push
             * @example pull_request
             * @example issues
             */
            event: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** External Id */
            external_id?: string | null;
        };
        /** Totals */
        Totals: {
            /**
             * Findings Total
             * @default 0
             */
            findings_total: number;
            /**
             * Findings Open
             * @default 0
             */
            findings_open: number;
            /**
             * Findings Actioned
             * @default 0
             */
            findings_actioned: number;
            /**
             * Findings Dismissed
             * @default 0
             */
            findings_dismissed: number;
            /**
             * Fixes Proposed
             * @default 0
             */
            fixes_proposed: number;
            /**
             * Prs Opened
             * @default 0
             */
            prs_opened: number;
            /**
             * Fixes Blocked
             * @default 0
             */
            fixes_blocked: number;
        };
        /**
         * UserOut
         * @description Safe user fields — never includes access_token.
         */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Github Id */
            github_id: number;
            /** Login */
            login: string;
            /** Name */
            name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Email */
            email: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    github_login_api_auth_github_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    github_callback_api_auth_github_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                installation_id?: number | null;
                setup_action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    connect_repo_api_repos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repo_api_repos__repo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_repos__repo_id__entities_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["EntityKind"] | null;
                /** @description search name/path */
                q?: string | null;
                sort?: "name" | "path" | "kind" | "updated_at";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_repos__repo_id__findings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FindingStatus"] | null;
                severity?: components["schemas"]["FindingSeverity"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_action_api_findings__finding_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    available_repos_api_github_available_repos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableReposOut"];
                };
            };
        };
    };
    list_pulls_api_repos__repo_id__pulls_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_repos__repo_id__pulls__pr_number__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
                pr_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_review_api_repos__repo_id__pulls__pr_number__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
                pr_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_review_api_repos__repo_id__pulls__pr_number__review_post_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
                pr_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_api_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-github-event"?: string;
                "x-github-delivery"?: string;
                "x-hub-signature-256"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_event_api_repos__repo_id__simulate_event_post: {
        parameters: {
            query?: never;
            header?: {
                "x-axon-simulate-secret"?: string | null;
            };
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
