"""Add uq_events_repo_external constraint

Revision ID: 2b883e7a16d0
Revises: 
Create Date: 2026-07-20 23:15:15.876928
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b883e7a16d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_events_repo_external', 'events', ['repo_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_events_repo_external', 'events', type_='unique')
    # ### end Alembic commands ###
